scrape_configs:
  - job_name: 'SecondMemoryMetrics'
    metrics_path: 'admin/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Second Memory Application'
