spring:
  application:
    name: secondMemory

  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: changeme

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
