create table if not exists file
(
    id       bigint generated by default as identity,
    capacity bigint      not null,
    name     varchar(50) not null,
    constraint PK_file primary key (id)
);

