create table if not exists users
(
    id       bigint primary key generated by default as identity,
    email    varchar(30) not null,
    name     varchar(30) not null,
    password varchar(80) not null
);

create table if not exists sessions
(
    id      bigint primary key generated by default as identity,
    cookie  varchar(68) not null,
    user_id bigint,
    foreign key (user_id) references users (id)
);

create table if not exists buckets
(
    id   bigint primary key generated by default as identity,
    name varchar(30) not null unique
);

create table if not exists files_info
(
    id                 bigint primary key generated by default as identity,
    capacity           bigint      not null,
    name               varchar(50) not null,
    creation_date      timestamp   not null,
    last_modified_date timestamp   not null,
    owner_id           bigint      not null,
    bucket_id          bigint      not null,
    foreign key (owner_id) references users (id),
    foreign key (bucket_id) references buckets (id) on delete cascade
);

create table if not exists tags
(
    id   bigint primary key generated by default as identity,
    name varchar(30) not null
);

create table if not exists files_tags
(
    file_id bigint,
    tag_id  bigint,
    primary key (file_id, tag_id),
    foreign key (file_id) references files_info (id),
    foreign key (tag_id) references tags (id)
);

create table if not exists files_roles (
    id bigint primary key generated by default as identity,
    user_id bigint references users (id) not null,
    file_id BIGINT REFERENCES files_info (id)  NOT NULL,
    type    VARCHAR(50)                  NOT NULL,
    UNIQUE (user_id, post_id, type)
);
