CREATE TABLE IF NOT EXISTS files_info (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    owner_id BIGINT NOT NULL,
--     FOREIGN KEY(owner_id) REFERENCES users(id),
    creation_date TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP NOT NULL,
    access_level_id BIGINT NOT NULL
--     FOREIGN KEY(access_level_id) REFERENCES roles(id)
)