CREATE TABLE IF NOT EXISTS files_info (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_name VARCHAR NOT NULL,
    file_owner_id VARCHAR NOT NULL,
    file_creation_date VARCHAR NOT NULL,
    file_last_modified_date VARCHAR NOT NULL,
    file_access_level VARCHAR NOT NULL,
    file_tags VARCHAR,
    CONSTRAINT PK_files PRIMARY KEY (file_id)
)