CREATE TABLE IF NOT EXISTS files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users (id),
    creation_date TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP NOT NULL,
    access_level VARCHAR(30) NOT NULL,
    tags VARCHAR(50),
    CONSTRAINT PK_files PRIMARY KEY (id)
);
